---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-management-secrets
              key: db_root_password
        ports:
        - containerPort: 5432
          name: db-container
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgres
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: postgres
  selector:
    app: db
  type: NodePort